// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_viamatica.Data;

#nullable disable

namespace Prueba_viamatica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202230355_AjusteVariableDuracion")]
    partial class AjusteVariableDuracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prueba_viamatica.Models.Entities.Pelicula", b =>
                {
                    b.Property<int>("IdPelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPelicula"));

                    b.Property<float>("Duracion")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPelicula");

                    b.ToTable("pelicula", (string)null);
                });

            modelBuilder.Entity("Prueba_viamatica.Models.Entities.PeliculaSalaCine", b =>
                {
                    b.Property<int>("IdPeliculaSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeliculaSala"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("int");

                    b.Property<int>("IdSalaCine")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("IdPeliculaSala");

                    b.HasIndex("IdPelicula");

                    b.HasIndex("IdSalaCine");

                    b.ToTable("pelicula_salacine", (string)null);
                });

            modelBuilder.Entity("Prueba_viamatica.Models.Entities.SalaCine", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSala"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSala");

                    b.ToTable("sala_cine", (string)null);
                });

            modelBuilder.Entity("Prueba_viamatica.Models.Entities.PeliculaSalaCine", b =>
                {
                    b.HasOne("Prueba_viamatica.Models.Entities.Pelicula", "Pelicula")
                        .WithMany("PeliculasSalaCine")
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prueba_viamatica.Models.Entities.SalaCine", "SalaCine")
                        .WithMany("PeliculasSalaCine")
                        .HasForeignKey("IdSalaCine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("SalaCine");
                });

            modelBuilder.Entity("Prueba_viamatica.Models.Entities.Pelicula", b =>
                {
                    b.Navigation("PeliculasSalaCine");
                });

            modelBuilder.Entity("Prueba_viamatica.Models.Entities.SalaCine", b =>
                {
                    b.Navigation("PeliculasSalaCine");
                });
#pragma warning restore 612, 618
        }
    }
}
